namespace H3Lib.StaticData
{
    public static class Vertex
    {
        /// <summary>
        /// Invalid vertex number
        /// </summary>
        public const int INVALID_VERTEX_NUM = -1;

        /// <summary>
        /// Max number of faces a base cell's descendants may appear on
        /// </summary>
        public const int MAX_BASE_CELL_FACES = 5;

        public const int DIRECTION_INDEX_OFFSET = 2;

        /// <summary>
        /// Table of direction-to-face mapping for each pentagon
        ///
        /// Note that faces are in directional order, starting at J_AXES_DIGIT.
        /// This table is generated by the generatePentagonDirectionFaces script.
        /// </summary>
        /// <remarks>
        /// TODO: Need to create generatePentagonDirectionFaces script equivalent
        /// </remarks>
        /// <!--
        /// vertex.c
        /// -->
        public static readonly PentagonDirectionFace[] PentagonDirectionFaces =
        {
            new PentagonDirectionFace(4, 4, 0, 2, 1, 3),
            new PentagonDirectionFace(14, 6, 11, 2, 7, 1),
            new PentagonDirectionFace(24, 5, 10, 1, 6, 0),
            new PentagonDirectionFace(38, 7, 12, 3, 8, 2),
            new PentagonDirectionFace(49, 9, 14, 0, 5, 4),
            new PentagonDirectionFace(58, 8, 13, 4, 9, 3),
            new PentagonDirectionFace(63, 11, 6, 15, 10, 16),
            new PentagonDirectionFace(72, 12, 7, 16, 11, 17),
            new PentagonDirectionFace(83, 10, 5, 19, 14, 15),
            new PentagonDirectionFace(97, 13, 8, 17, 12, 18),
            new PentagonDirectionFace(107, 14, 9, 18, 13, 19),
            new PentagonDirectionFace(117, 15, 19, 17, 18, 16),
        };

        /// <summary>
        /// Hexagon direction to vertex number relationships (same face).
        ///
        /// Note that we don't use direction 0 (center).
        /// </summary>
        public static int[] DirectionToVertexNumHex =
            {(int) Direction.INVALID_DIGIT, 3, 1, 2, 5, 4, 0};

        /// <summary>
        /// Pentagon direction to vertex number relationships (same face).
        /// Note that we don't use directions 0 (center) or 1 (deleted K axis).
        /// </summary>
        public static int[] DirectionToVertexNumPent =
            {(int) Direction.INVALID_DIGIT, (int) Direction.INVALID_DIGIT, 1, 2, 4, 3, 0};

    }
}
