@startuml


class FaceIjk
{
   + int Face
   + CoordIjk Coord
   + FaceIjk(int f, CoordIjk cijk)
   + FaceIjk(FaceIjk fijk)
    
}

class FaceIjkExtensions
{
    + FaceIjk ReplaceFace(this FaceIjk fijk, int face)
    + FaceIjk ReplaceFace(this FaceIjk fijk, CoordIjk coord)
    + (Overage, FaceIjk) AdjustOverageClassIi(this FaceIjk fijk, int res, int pentLeading4, int substrate)
    + public static (Overage, FaceIjk) AdjustPentOverage(this FaceIjk fijk, int res)
    + public static (FaceIjk, int, IList<FaceIjk>) PentToVerts(this FaceIjk fijk, int res, IList<FaceIjk> fijkVerts)
    + public static (FaceIjk, int, IList<FaceIjk>) ToVerts(this FaceIjk fijk, int res, IList<FaceIjk> fijkVerts)
    + public static H3Index ToH3(this FaceIjk fijk, int res)
    + public static int ToBaseCell(this FaceIjk h)
    + public static int ToBaseCellCounterClockwiseRotate60(this FaceIjk h)
    + public static GeoCoord ToGeoCoord(this FaceIjk h, int res)
    + public static GeoBoundary ToGeoBoundary(this FaceIjk h, int res, int start, int length)
    + public static GeoBoundary PentToGeoBoundary(this FaceIjk h, int res, int start, int length)
}

FaceIjk - FaceIjkExtensions : Extended by >
@enduml
