name: .NET

on:
  push:
    branches: [ v3.7.1 ]
  pull_request:
    branches: [ v3.7.1 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run Tests
      run: dotnet test --logger:nunit
  
